### ISSUE TITLE
"./macfuse_buildtool.sh -t reload" does not work

### ISSUE THREAD

**Issue by anatol** [bfleischer/macfuse#1]
It says "kextload" does not have -s parameter. I guess "kextutil -s" should be used in macfuse_buildtool.sh

But even with this change on my machine it fails with:

=== BUILD NATIVE TARGET fusefs OF PROJECT fusefs WITH CONFIGURATION Debug ===
Check dependencies

*\* BUILD SUCCEEDED **

MacFUSEBuildTool(reload)      : reloading kext
Notice: Using running kernel architecture i386 to generate symbols.
Warnings: 
    Executable does not contain code for architecture: 
        i386

/tmp/fusefs.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /tmp/fusefs.kext.
Can't load /tmp/fusefs.kext - no code for running kernel's architecture.
Failed to load /tmp/fusefs.kext - (libkern/kext) requested architecture/executable not found.
Failed to load /tmp/fusefs.kext - (libkern/kext) requested architecture/executable not found.
MacFUSEBuildTool(reload) failed: cannot load newly built MacFUSE kext.

**Comment by bfleischer** [comment]
Which kernel do you use, 32 bit or 64 bit?

**Comment by anatol** [comment]
32 bits

$ uname -a
Darwin foobar.mycompany.com 10.7.0 Darwin Kernel Version 10.7.0: Sat Jan 29 15:17:16 PST 2011; root:xnu-1504.9.37~1/RELEASE_I386 i386

macosx version == 10.6.7

**Comment by bfleischer** [comment]
You are right, it has to be "kextutil -s" not "kextload -s". Apple has moved some options of kextload to kextutil in 10.6. Everything should be fine now. Thanks!
