### ISSUE TITLE
"./macfuse_buildtool.sh -t examples" fails

### ISSUE THREAD

**Issue by anatol** [bfleischer/macfuse#2]
I try to run this command on 64bit kernel

$ ./macfuse_buildtool.sh -t examples

and it fails:
config.status: creating lib/Makefile
config.status: creating util/Makefile
config.status: creating include/Makefile
config.status: creating include/config.h
config.status: include/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
Can't open Makefile: No such file or directory.
MacFUSEBuildTool(examples)    : running make
make: **\* No targets specified and no makefile found.  Stop.
MacFUSEBuildTool(examples) failed: make failed while compiling the MacFUSE examples.

**Comment by anatol** [comment]
It seems the problem is that this folder https://github.com/bfleischer/fuse/tree/fuse-2.8.5-macfuse/example does not contain Makefile

**Comment by bfleischer** [comment]
Examples should work now. But all new examples (that were not present in FUSE 2.7.3) have been disabled.
